#!/usr/bin/env bash
set -euo pipefail

function main {
  local image
  if [[ "$#" -ne 0 ]]; then
    display_help "$@"
  else
    cd "$HOME/.fluxbox/background/"
    image="$(echo "$IMAGES" | shuf --head-count=1)"
    curl --location --remote-name "$image"
  fi
}

function display_help {
  cat <<EOF
Usage:
  $(basename "${BASH_SOURCE[0]}")

Fetches a random password
EOF
  return 1
}

# Image url fetching commands:
# Imgur: curl https://imgur.com/gallery/<GALLERY>.json | jq --raw-output '.data.image.album_images.images[] | "https://i.imgur.com/" + .hash + .ext'

# Images included below:
# https://imgur.com/gallery/Ytp5l.json

read -r -d '' IMAGES << 'EOM' || true
https://i.imgur.com/010Fthr.jpg
https://i.imgur.com/03HnLm2.jpg
https://i.imgur.com/0dIcm1h.jpg
https://i.imgur.com/0hu0Cqq.jpg
https://i.imgur.com/0KbQpjS.jpg
https://i.imgur.com/0mUcF4N.jpg
https://i.imgur.com/0sf4cP9.png
https://i.imgur.com/0xXVH01.jpg
https://i.imgur.com/1hQv4Ff.jpg
https://i.imgur.com/1OByf2m.png
https://i.imgur.com/1y1cMG2.jpg
https://i.imgur.com/20CIEWE.jpg
https://i.imgur.com/2DvmshV.jpg
https://i.imgur.com/2ONpris.jpg
https://i.imgur.com/2TpoTYb.jpg
https://i.imgur.com/2vj4rRJ.jpg
https://i.imgur.com/32ZTBCi.png
https://i.imgur.com/3iVUCXB.jpg
https://i.imgur.com/3XOMui4.jpg
https://i.imgur.com/4aGz1jS.jpg
https://i.imgur.com/4GTjzVc.jpg
https://i.imgur.com/4iQFY5j.png
https://i.imgur.com/4LLE9cy.jpg
https://i.imgur.com/4SSkzXN.jpg
https://i.imgur.com/4uY95sI.jpg
https://i.imgur.com/4zpVHSE.jpg
https://i.imgur.com/5Sw5ZtG.png
https://i.imgur.com/5TENTLf.jpg
https://i.imgur.com/62rUWTQ.jpg
https://i.imgur.com/6heiHqL.jpg
https://i.imgur.com/6tUS1pZ.png
https://i.imgur.com/7sVcHGX.jpg
https://i.imgur.com/7WKQLem.jpg
https://i.imgur.com/7ZvYhU2.jpg
https://i.imgur.com/89c1du2.jpg
https://i.imgur.com/8csLogx.png
https://i.imgur.com/9bx5o5u.jpg
https://i.imgur.com/9cNoMuP.jpg
https://i.imgur.com/9ekF4Pc.jpg
https://i.imgur.com/9sBVueW.jpg
https://i.imgur.com/a33dmjq.jpg
https://i.imgur.com/ABkUlcw.jpg
https://i.imgur.com/acof2oc.jpg
https://i.imgur.com/acPgUbs.jpg
https://i.imgur.com/Ak8VHV9.png
https://i.imgur.com/aSW1Hxw.jpg
https://i.imgur.com/at5Yt6C.jpg
https://i.imgur.com/aUkphtw.jpg
https://i.imgur.com/B1eZZuD.jpg
https://i.imgur.com/bFb8RAc.jpg
https://i.imgur.com/BpTwvHA.jpg
https://i.imgur.com/BpvOWVq.jpg
https://i.imgur.com/BqUm8kz.jpg
https://i.imgur.com/BsNon1a.png
https://i.imgur.com/bsXLNLn.jpg
https://i.imgur.com/BxVT6YR.jpg
https://i.imgur.com/C2odIFm.jpg
https://i.imgur.com/C3os16P.jpg
https://i.imgur.com/CA63Qkm.jpg
https://i.imgur.com/crOeaSr.jpg
https://i.imgur.com/ctxlDCe.png
https://i.imgur.com/cvGelX1.jpg
https://i.imgur.com/D6zgYd9.jpg
https://i.imgur.com/dIMRN62.jpg
https://i.imgur.com/DjQV6ea.jpg
https://i.imgur.com/DK1LrpZ.jpg
https://i.imgur.com/DpNsgCF.jpg
https://i.imgur.com/dtiBXl7.jpg
https://i.imgur.com/DwBT13d.jpg
https://i.imgur.com/DYGfAcr.jpg
https://i.imgur.com/e2mZAbD.jpg
https://i.imgur.com/EAHRidh.jpg
https://i.imgur.com/efIrzyg.jpg
https://i.imgur.com/eg4iDIC.jpg
https://i.imgur.com/EoBzeAS.jpg
https://i.imgur.com/EOsPUij.jpg
https://i.imgur.com/Eptr79o.jpg
https://i.imgur.com/fCFrl2j.jpg
https://i.imgur.com/FyHF0dp.png
https://i.imgur.com/geAe6B7.png
https://i.imgur.com/GG4oOuq.jpg
https://i.imgur.com/gGplOAV.jpg
https://i.imgur.com/gkk2lRt.jpg
https://i.imgur.com/GMHjnGi.jpg
https://i.imgur.com/GvB8KLd.jpg
https://i.imgur.com/gvTNDx1.jpg
https://i.imgur.com/gy2jHII.jpg
https://i.imgur.com/gZuRIrb.jpg
https://i.imgur.com/h3A3aIN.jpg
https://i.imgur.com/hjX5p1u.jpg
https://i.imgur.com/hTqryZY.jpg
https://i.imgur.com/HVtFzWG.png
https://i.imgur.com/HW3g9tJ.jpg
https://i.imgur.com/hWe2hSE.png
https://i.imgur.com/Hy23XKX.jpg
https://i.imgur.com/HyTmvna.jpg
https://i.imgur.com/Hzvn1Sa.jpg
https://i.imgur.com/iaZ7BnP.jpg
https://i.imgur.com/IiNIXbG.png
https://i.imgur.com/IIprHhw.jpg
https://i.imgur.com/IJqTOLk.jpg
https://i.imgur.com/IKFKDcS.jpg
https://i.imgur.com/IKNmrCI.jpg
https://i.imgur.com/ikWYK2p.jpg
https://i.imgur.com/IOLbL3o.jpg
https://i.imgur.com/IrIC333.jpg
https://i.imgur.com/iv3uTxw.jpg
https://i.imgur.com/jEHzFrt.jpg
https://i.imgur.com/jhEXJvq.jpg
https://i.imgur.com/JUdyKwx.jpg
https://i.imgur.com/Jut1DQr.jpg
https://i.imgur.com/k5jzagB.png
https://i.imgur.com/K6Ef6gD.jpg
https://i.imgur.com/KcQ6SFZ.png
https://i.imgur.com/kENkUGv.jpg
https://i.imgur.com/KFrsfb4.jpg
https://i.imgur.com/kWZfwp0.jpg
https://i.imgur.com/kXIBzo9.jpg
https://i.imgur.com/l0nr0XV.jpg
https://i.imgur.com/l3wYCvK.jpg
https://i.imgur.com/L6hax1p.jpg
https://i.imgur.com/l6xac1G.jpg
https://i.imgur.com/LPCPILw.jpg
https://i.imgur.com/lrRGyBP.jpg
https://i.imgur.com/lTzD3TV.jpg
https://i.imgur.com/m2dq5Qs.jpg
https://i.imgur.com/M4JkEyA.jpg
https://i.imgur.com/MaaolDt.jpg
https://i.imgur.com/MBNFSs3.jpg
https://i.imgur.com/MggbiRW.jpg
https://i.imgur.com/Mh3DKDO.jpg
https://i.imgur.com/misZgdZ.jpg
https://i.imgur.com/MKxUc8r.jpg
https://i.imgur.com/mmxLa9x.png
https://i.imgur.com/mq5B7fD.jpg
https://i.imgur.com/mVSkRle.jpg
https://i.imgur.com/n6VwoTd.jpg
https://i.imgur.com/NLw099I.jpg
https://i.imgur.com/nQFKH0h.jpg
https://i.imgur.com/NU03zXJ.jpg
https://i.imgur.com/Ny6wp5C.jpg
https://i.imgur.com/NZJhiE1.jpg
https://i.imgur.com/o2Wm9LI.jpg
https://i.imgur.com/OiNLP58.jpg
https://i.imgur.com/OL15b81.jpg
https://i.imgur.com/om1C9Wp.jpg
https://i.imgur.com/onzR9xo.jpg
https://i.imgur.com/OwsS2un.png
https://i.imgur.com/oYeY2mu.jpg
https://i.imgur.com/P0vh30i.jpg
https://i.imgur.com/pH0ud25.jpg
https://i.imgur.com/PIacSIX.png
https://i.imgur.com/PJeePx2.jpg
https://i.imgur.com/pN7cmn5.jpg
https://i.imgur.com/QBpumcA.jpg
https://i.imgur.com/QDwKm0y.jpg
https://i.imgur.com/QobxGJF.jpg
https://i.imgur.com/qPZEJ9C.jpg
https://i.imgur.com/QS6QMsN.jpg
https://i.imgur.com/r8Ddhtb.jpg
https://i.imgur.com/RCXn2p6.jpg
https://i.imgur.com/rDFuIJA.png
https://i.imgur.com/rdZ0ucn.jpg
https://i.imgur.com/RGtxHTu.jpg
https://i.imgur.com/rhr36Xh.jpg
https://i.imgur.com/RhtJRnJ.jpg
https://i.imgur.com/rnxAIFY.png
https://i.imgur.com/RuYHDbi.jpg
https://i.imgur.com/rVLISf2.jpg
https://i.imgur.com/RWK6EMa.jpg
https://i.imgur.com/RzGak4d.jpg
https://i.imgur.com/S7o9l4q.jpg
https://i.imgur.com/SE6KFfI.jpg
https://i.imgur.com/Sfd3xsP.jpg
https://i.imgur.com/sHWuy2U.jpg
https://i.imgur.com/ss3fBsU.png
https://i.imgur.com/sSNnBzJ.jpg
https://i.imgur.com/Swe2Jap.png
https://i.imgur.com/sYTL7LT.jpg
https://i.imgur.com/TB0btBH.jpg
https://i.imgur.com/Td9pdha.jpg
https://i.imgur.com/TdTHvog.jpg
https://i.imgur.com/TgfzVKL.jpg
https://i.imgur.com/tIttCTh.jpg
https://i.imgur.com/TJzPjP9.jpg
https://i.imgur.com/tnJCjEF.jpg
https://i.imgur.com/tTVyb4U.jpg
https://i.imgur.com/TvQg5zk.jpg
https://i.imgur.com/tWTasLJ.png
https://i.imgur.com/tYcmMFZ.jpg
https://i.imgur.com/ua4Fa15.jpg
https://i.imgur.com/UFcgH51.jpg
https://i.imgur.com/uGYGbDv.jpg
https://i.imgur.com/uoSIRc3.png
https://i.imgur.com/uPsnxXp.png
https://i.imgur.com/uRqgVaV.jpg
https://i.imgur.com/UtA6lUK.jpg
https://i.imgur.com/uzKomen.jpg
https://i.imgur.com/V2uAltT.jpg
https://i.imgur.com/V5TTNvk.jpg
https://i.imgur.com/v9j8XvI.png
https://i.imgur.com/VCXoLtp.jpg
https://i.imgur.com/vi4HnyW.jpg
https://i.imgur.com/vpn86Ik.jpg
https://i.imgur.com/VRohe2Q.jpg
https://i.imgur.com/vZAsRp4.jpg
https://i.imgur.com/w4hrkpJ.jpg
https://i.imgur.com/W7GtcYa.png
https://i.imgur.com/wCE7Fpz.png
https://i.imgur.com/wUvpAHq.jpg
https://i.imgur.com/WYQ2ofN.jpg
https://i.imgur.com/x8uKu3E.jpg
https://i.imgur.com/xaoS0Ww.jpg
https://i.imgur.com/XdtolXR.jpg
https://i.imgur.com/XghEQlO.jpg
https://i.imgur.com/XnQFqph.jpg
https://i.imgur.com/xP06zQu.png
https://i.imgur.com/Xrv05XI.jpg
https://i.imgur.com/xvpxjts.jpg
https://i.imgur.com/XxhS1rd.jpg
https://i.imgur.com/Y3khC9y.jpg
https://i.imgur.com/Y6uQZ6F.png
https://i.imgur.com/y9pEzDq.jpg
https://i.imgur.com/yESgkT8.jpg
https://i.imgur.com/yhivlPe.jpg
https://i.imgur.com/YkcryCJ.jpg
https://i.imgur.com/YvsyVY2.jpg
https://i.imgur.com/yxhUP2U.jpg
https://i.imgur.com/ZdATXkt.png
https://i.imgur.com/ZkoIQwC.png
https://i.imgur.com/zp0iy4s.jpg
https://i.imgur.com/ZP5XbrW.jpg
https://i.imgur.com/zQBrkFc.jpg
https://i.imgur.com/ZXirOTr.jpg
https://i.imgur.com/ZzhHqxV.jpg
EOM

main "$@"
