#!/usr/bin/env bash
set -euo pipefail

AUTH_GROUP='VPN-Policy-OneLogin-BYOD-IT'
PID_FILE='/var/run/openconnect.pid'
SERVER_CERTIFICATE='pin-sha256:845k6dzZ+MIu9goIyGPoTLgeopHTFYAPJw5zbUpNG2A='
SERVER='vpn1.echo.com'

function main {
  sudo openconnect "$SERVER" \
    --authgroup="$AUTH_GROUP" \
    --background \
    --pid-file "$PID_FILE" \
    --servercert="$SERVER_CERTIFICATE"
}

main "$@"
