---
- name: 'configure_firewall : Install packages'
  package:
    name:
    - ufw
- name: 'configure_firewall : Deny incoming traffic by default'
  ufw:
    default: deny
- name: 'configure_firewall : Limit ssh traffic'
  ufw:
    direction: in
    proto: tcp
    rule: limit
    to_port: ssh
- name: 'configure_firewall : Start and enable firewall'
  ufw:
    state: enabled
