---
- name: 'configure_firewall : ufw : Install packages'
  package:
    name:
    - ufw
- name: 'configure_firewall : ufw : Deny incoming traffic by default'
  ufw:
    default: deny
- name: 'configure_firewall : ufw : Limit ssh traffic'
  ufw:
    direction: in
    proto: tcp
    rule: limit
    to_port: ssh
- name: 'configure_firewall : ufw : Start and enable firewall'
  ufw:
    state: enabled
- name: 'configure_firewall : ufw : Start and enable firewall for real (ufw bug)'
  service:
    enabled: 'yes'
    name: ufw
    state: started
