---
- lineinfile:
    line: PermitRootLogin no
    path: /etc/ssh/sshd_config
    regexp: '^(# )?PermitRootLogin '
  name: 'configure_sshd : Disable root access'
- name: 'configure_sshd : Restart and enable sshd'
  service:
    enabled: 'yes'
    name: sshd
    state: restarted
