---
- k8s:
    apply: 'yes'
    definition: '{{ lookup("file", "default_network_policy.yml") }}'
    kubeconfig: /etc/kubernetes/admin.conf
  name: 'apply_base_resources : Apply default network policy'
  when: '"primary_master" in group_names'
- changed_when: false
  k8s:
    definition: '{{ lookup("file", "default_network_policy.yml") }}'
    kubeconfig: /etc/kubernetes/admin.conf
    wait: 'yes'
  name: 'apply_base_resources : Wait for resources to become ready'
  when: '"primary_master" in group_names'
