#!/bin/bash

function move_window {
  name="$1"
  position="$2"
  size="$3"

  # Wait for the window to appear
  count=0
  while ! wmctrl -l | grep -i "$name"; do
    sleep 1
    count="$((count + 1))"
    if [ "$count" -gt 100 ]; then
      echo "Failed to locate window named '$name'"
      return 1
    fi
  done

  # Position it
  wmctrl -r "$name" -e "0,$position,$size"
}

function eval_if_command {
  if command -v "$1"; then
    "$@"
  fi
}

# Load Keymap
xmodmap "/home/dan/.Xmodmap"
# Start Virtualbox guest additions
eval_if_command VBoxClient-all
# Fetch a new background
eval_if_command fetchbackground &
# Enable numlock
eval_if_command numlockx &
# Clock
eval_if_command xclock -strftime '%A %m/%d/%Y %I:%M:%S %p' &

# Set background
if [[ -f ~/.fluxbox/background/default.png ]]; then
  setbackground ~/.fluxbox/background/default.png
else
  eval_if_command fetchbackground &
fi

# Stuff I use every time
case "$(hostname)" in
glados)
  # Weekends
  if [[ "$(date +%A)" =~ ^(Saturday|Sunday)$ ]]; then
    firefox &
    xterm &
    code ~/projects/ &
    move_window firefox 0,0    1135,1440 &
    move_window xterm   1135,0 1170,864 &
    move_window code    2305,0 1135,1440 &
  # Weekdays
  else
    hour="$(date +%H)"
    if [[ "$hour" -lt 6 ]]; then
      true
    elif [[ "$hour" -lt 4 ]]; then
      vlc &
      virtualbox &
      firefox &
      teams &
      move_window vlc        0,0      1135,1440 &
      move_window virtualbox 1135,0   1170,864 &
      move_window firefox    1135,864 1170,576 &
      move_window teams      2305,0   1135,1440 &
    else
      firefox &
      xterm &
      code ~/projects/ &
      move_window firefox 0,0    1135,1440 &
      move_window xterm   1135,0 1170,1440 &
      move_window code    2305,0 1135,1440 &
    fi
  fi
  ;;
dev.wrk.danivy.com)
  slack &
  code ~/projects/ &
  firefox &
  xterm &
  move_window slack   0,0      1135,1440 &
  move_window code    791,0    1514,1440 &
  move_window firefox 2305,0   1135,864 &
  move_window xterm   2305,864 1135,576 &
  ;;
esac

# Run fluxbox
exec fluxbox
# exec fluxbox -log "/home/dan/.fluxbox/log"
