---
- name: Install packages
  package:
    name:
    - sudo
- group:
    name: sudo
  name: Create sudo group
- group:
    name: '{{ development.user.name }}'
  name: Create user groups
- name: Create user
  user:
    append: 'yes'
    group: '{{ development.user.name }}'
    groups: '{{ development.user.groups }}'
    name: '{{ development.user.name }}'
    password: '{{ development.user.password | password_hash(''sha512'') }}'
    update_password: on_create
- lineinfile:
    line: '%sudo ALL=(ALL) ALL'
    path: /etc/sudoers
  name: Grant sudo group sudo access
