---
- name: 'install_tools : Install packages'
  package:
    name:
    - base-devel # Base development tools
    - bind-tools # Network debugging tools
    - bmon # Network monitor
    - chromium # Internet browser
    - code # GUI text editor
    - docker # All the containers
    - dos2unix # Convert LF <==> CRLF
    - git # All the changes
    - gvim # Vim with mouse support in terminal
    - htop # System monitor
    - jq # JSON command line tool
    - kubectl # Kubernetes cluster controller
    - man # Manuals
    - nano # Basic text editor
    - nemo # File browser
    - nmap # Port scanning tool
    - shellcheck # Shell linter
    - tmux # Teminal multiplexer
    - ttf-dejavu # More fonts
    - unzip # Unzip zip files
    - zip # Zip zip files
- get_url:
    checksum: '{{ development.install_tools.yq.checksum }}'
    dest: /usr/local/bin/yq
    group: root
    mode: '755'
    owner: root
    url: >-
      https://github.com/mikefarah/yq/releases/download/{{
      development.install_tools.yq.version }}/yq_linux_amd64
  name: 'install_tools : Install yq'
- loop:
  - docker
  name: 'install_tools : Enable services'
  service:
    enabled: 'yes'
    name: '{{ item }}'
    state: started
- include_tasks: add_config_module.yml
  loop:
  - nano
  - scripts
  - vim
  vars:
    become_user: root
    config_module: '{{ item }}'
- include_tasks: add_config_module.yml
  loop:
  - bash
  - chromium
  - code
  - git
  - ssh
  vars:
    become_user: '{{ development.user.name }}'
    config_module: '{{ item }}'
- become_user: '{{ development.user.name }}'
  file:
    mode: '755'
    owner: '{{ development.user.name }}'
    path: '{{ item }}'
    state: directory
  loop:
  - '/home/{{ development.user.name }}/downloads'
  - '/home/{{ development.user.name }}/projects'
  name: 'install_tools : Create directories'
