---
- name: 'install_minikube : Install packages'
  package:
    name:
    - kubectl
    - minikube
- become_user: '{{ item }}'
  loop: '{{ development.dev_users }}'
  name: 'install_minikube : Set vm-driver'
  shell:
    cmd: minikube config set vm-driver docker
