---
- name: 'install_tools : Install packages'
  package:
    name:
    - base-devel # Base development tools
    - bind-tools # Network debugging tools
    - bmon # Network monitor
    - chromium # Internet browser
    - code # GUI text editor
    - dos2unix # Convert LF <==> CRLF
    - expect # Make scripts pretend they're human
    - git # All the changes
    - gvim # Vim with mouse support in terminal
    - htop # System monitor
    - jq # JSON command line tool
    - man # Manuals
    - nano # Basic text editor
    - nemo # File browser
    - nmap # Port scanning tool
    - shellcheck # Shell linter
    - tmux # Teminal multiplexer
    - ttf-dejavu # More fonts
    - unzip # Unzip zip files
    - zip # Zip zip files
- get_url:
    checksum: '{{ development.install_tools.yq.checksum }}'
    dest: /usr/local/bin/yq
    group: root
    mode: '755'
    owner: root
    url: >-
      https://github.com/mikefarah/yq/releases/download/{{
      development.install_tools.yq.version }}/yq_linux_amd64
  name: 'install_tools : Install yq'
- include_tasks: add_config_modules.yml
  vars:
    modules:
    - nano
    - scripts
    - vim
    users:
    - root
- include_tasks: add_config_modules.yml
  vars:
    modules:
    - bash
    - chromium
    - code
    - git
    - ssh
    users: '{{ development.dev_users }}'
- become_user: '{{ item[0] }}'
  file:
    mode: '755'
    owner: '{{ item[0] }}'
    path: '{{ item[1] }}'
    state: directory
  name: 'install_tools : Create directories'
  with_nested:
  - '{{ development.dev_users }}'
  - - '~/downloads'
    - '~/projects'
