---
- name: 'install openshift'
  pip:
    name: openshift
- changed_when: false
  name: 'Generate resource definition'
  register: resources
  shell:
    cmd: >-
      find
      /tmp/kubernetes-apps/kubernetes-manifests/all/
      /tmp/kubernetes-apps/kubernetes-manifests/{{ env }}/
      -type f -name '*.yml' | xargs cat
    executable: sh
- k8s:
    apply: 'yes'
    definition: '{{ resources.stdout }}'
    state: '{{ "present" if mode == "apply" else "absent" }}'
  name: '{{ "Apply" if mode == "apply" else "Delete" }} resources'
- changed_when: false
  k8s:
    definition: '{{ resources.stdout }}'
    state: '{{ "present" if mode == "apply" else "absent" }}'
    wait: 'yes'
    wait_timeout: 300 # wait 5 min for everything to come up
  name: 'Wait change to take effect'
