---
- name: 'Add yum repo'
  yum_repository:
    baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch'
    description: kubernetes
    exclude:
    - kubeadm
    - kubectl
    - kubelet
    gpgcheck: 'yes'
    gpgkey:
    - 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'
    - 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
    name: kubernetes
    repo_gpgcheck: 'yes'
- name: 'Set selinux to permissive'
  selinux:
    policy: targeted
    state: permissive
- name: 'Install packages'
  yum:
    disable_excludes: kubernetes
    name:
    - 'kubeadm-{{ k8s_setup.kube_version }}'
    - 'kubectl-{{ k8s_setup.kube_version }}'
    - 'kubelet-{{ k8s_setup.kube_version }}'
    state: present
- name: 'Enable and start kubelet service'
  service:
    enabled: 'yes'
    name: kubelet
    state: started
- file:
    path: /root/.kube/
    state: directory
  name: 'Create /root/.kube/ directory'
- file:
    dest: /root/.kube/config
    follow: 'no'
    force: 'yes'
    group: root
    owner: root
    src: /etc/kubernetes/admin.conf
    state: link
  name: 'Link /root/.kube/config to admin config'
