---
- k8s:
    apply: 'yes'
    definition: '{{ lookup("template", "nginx_ingress_baremetal.yaml.j2") }}'
    kubeconfig: /etc/kubernetes/admin.conf
  name: 'Apply nginx ingress controller'
  when: '"primary_master" in group_names'
- changed_when: false
  k8s:
    definition: '{{ lookup("template", "nginx_ingress_baremetal.yaml.j2") }}'
    kubeconfig: /etc/kubernetes/admin.conf
    wait: 'yes'
  name: 'Wait for resources to become ready'
  when: '"primary_master" in group_names'
