---
- include_tasks: install_tools.yml
- include_tasks: configure_firewall.yml
- include_tasks: configure_sshd.yml
- include_tasks: add_users.yml
- include_tasks: configure_root_user.yml
- include_tasks: enable_automatic_updates.yml
