---
- k8s:
    apply: 'yes'
    definition: '{{ lookup("file", "storage_classes.yml") }}'
    kubeconfig: /etc/kubernetes/admin.conf
  name: 'Apply default network policy'
  when: '"primary_master" in group_names'
- changed_when: false
  k8s:
    definition: '{{ lookup("file", "storage_classes.yml") }}'
    kubeconfig: /etc/kubernetes/admin.conf
    wait: 'yes'
  name: 'Wait for resources to become ready'
  when: '"primary_master" in group_names'
