---
- name: 'install_tools : Install pacman packages'
  package:
    name:
    - freerdp # RDP protocol support for remmina
    - helm # An additional kubectl 
    - openconnect # Open source version of Cisco's AnyConnect
    - remmina # A remote connection manager

- name: 'install_tools : Install yay packages'
  become: yes
  become_user: aur_builder
  aur:
    name:
    - slack-desktop
    - sops
    - vmware-horizon-client

- name: 'install_tools : Copy startvpn script'
  copy:
    dest: /usr/local/bin/
    mode: '755'
    owner: root
    src: startvpn
  
- name: 'install_tools : Copy stopvpn script'
  copy:
    dest: /usr/local/bin/
    mode: '755'
    owner: root
    src: stopvpn
