---
- become: 'yes'
  environment:
    ftp_proxy: '{{ ftp_proxy | default() }}'
    http_proxy: '{{ http_proxy | default() }}'
    https_proxy: '{{ https_proxy | default() }}'
  hosts: k8s
  name: k8s_deploy
  roles:
  - k8s
  vars:
    app_deploy: no
    deploy: yes
    reset: no
    setup: no
