---
- become: 'yes'
  environment:
    ftp_proxy: '{{ ftp_proxy | default() }}'
    http_proxy: '{{ http_proxy | default() }}'
    https_proxy: '{{ https_proxy | default() }}'
  hosts: all
  name: packer_trigger_deploy
  roles:
  - packer_trigger
  vars:
    deploy: yes
    setup: no
