---
- become: 'yes'
  environment:
    ftp_proxy: '{{ ftp_proxy | default() }}'
    http_proxy: '{{ http_proxy | default() }}'
    https_proxy: '{{ https_proxy | default() }}'
  hosts: virtualbox_guest
  name: virtualbox_guest
  roles:
  - virtualbox_guest
