---
- include_tasks: install_fluxbox.yml
- include_tasks: install_tools.yml
- include_tasks: install_firefox.yml
- include_tasks: install_docker.yml
- include_tasks: install_minikube.yml
- include_tasks: add_config_modules.yml
  vars:
    modules:
    - fluxbox
    users: '{{ development.dev_users }}'
