#!/usr/bin/env bash
set -euo pipefail

AUTH_GROUP='VPN-Policy-OneLogin-BYOD-IT'
PID_FILE='/var/run/openconnect.pid'
SERVER_CERTIFICATE='pin-sha256:nCmyk2uNlIOV1RhIsy4eySzVoT0+QLh0eFA+j4pGTaA='
SERVER='vpn1.echo.com'

function main {
  sudo openconnect "$SERVER" \
    --authgroup="$AUTH_GROUP" \
    --background \
    --pid-file "$PID_FILE" \
    --servercert="$SERVER_CERTIFICATE"
}

main "$@"
