---
- modprobe:
    name: br_netfilter
  name: 'configure_firewall : Load br_netfilter module'
- lineinfile:
    create: 'yes'
    line: br_netfilter
    path: /etc/modules-load.d/br_netfilter.conf
  name: 'configure_firewall : Enable br_netfilter module'
- name: 'configure_firewall : Allow iptables to see bridged, ipv4 traffic'
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
- name: 'configure_firewall : Allow iptables to see bridged, ipv6 traffic'
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
