---
- name: 'install_packages : Add yum repo'
  yum_repository:
    baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch'
    description: kubernetes
    exclude:
    - kubeadm
    - kubectl
    - kubelet
    gpgcheck: 'yes'
    gpgkey:
    - 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'
    - 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
    name: kubernetes
    repo_gpgcheck: 'yes'
- name: 'install_packages : Set selinux to permissive'
  selinux:
    policy: targeted
    state: permissive
- name: 'install_packages : Install kube* packages and other tools'
  yum:
    disable_excludes: kubernetes
    name:
    - jq
    - 'kubeadm-{{ k8s_setup.kube_version }}'
    - 'kubectl-{{ k8s_setup.kube_version }}'
    - 'kubelet-{{ k8s_setup.kube_version }}'
    - tc
    state: present
- become_user: root
  copy:
    dest: /var/lib/kubelet/
    mode: '644'
    owner: root
    src: config.yaml
  name: 'install_packages : Copy kubelet config'
- name: 'install_packages : Enable and start kubelet service'
  service:
    enabled: 'yes'
    name: kubelet
    state: started
