---
- name: 'install_packages : Install useful tools'
  package:
    name:
    - jq
    - nmap
    - tc
    - telnet
    state: present
- name: 'install_packages : Install python modules'
  pip:
    name: openshift
