---
- name: 'main : Install packages'
  package:
    name:
    - virtualbox-guest-utils
    - xf86-video-vmware
- name: 'main : Enable vboxservice'
  service:
    enabled: 'yes'
    name: vboxservice
    state: started
