---
- lineinfile:
    line: PasswordAuthentication no
    path: /etc/ssh/sshd_config
    regexp: PasswordAuthentication (yes|no)
  name: 'configure_sshd : Disable password authentication'
  register: password_auth
- name: 'configure_sshd : Restart and enable sshd'
  service:
    enabled: 'yes'
    name: sshd
    state: restarted
  when: password_auth is changed
